file(MAKE_DIRECTORY "${WORK_DIR}")
set(script "${WORK_DIR}/startup with spaces.emu")
file(WRITE "${script}" "// startup\necho ready\ncd /home/alex\ntac notes.txt\nexit\n")
file(SHA256 "${FIXTURE_DIR}/commands.zip" original_hash)
execute_process(COMMAND "${EMULATOR}" --vfs-path "${FIXTURE_DIR}/commands.zip"
    --startup-script "${script}" RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT status EQUAL 0 OR NOT err STREQUAL "" OR NOT out MATCHES "third\nsecond\nfirst" OR out MATCHES "STUB")
    message(FATAL_ERROR "Startup failed: ${status}\n${out}\n${err}")
endif()
if(NOT out MATCHES "Startup script:" OR NOT out MATCHES "tac notes.txt")
    message(FATAL_ERROR "Configuration or simulated input missing")
endif()
foreach(arguments IN ITEMS missing_vfs missing_script bad_option)
    if(arguments STREQUAL "missing_vfs")
        set(args --vfs "${WORK_DIR}/absent.zip")
    elseif(arguments STREQUAL "missing_script")
        set(args --vfs "${FIXTURE_DIR}/commands.zip" --script "${WORK_DIR}/absent.emu")
    else()
        set(args --unknown)
    endif()
    execute_process(COMMAND "${EMULATOR}" ${args} RESULT_VARIABLE status OUTPUT_QUIET ERROR_VARIABLE err)
    if(status EQUAL 0 OR err STREQUAL "")
        message(FATAL_ERROR "Expected CLI failure: ${arguments}")
    endif()
endforeach()
file(SHA256 "${FIXTURE_DIR}/commands.zip" final_hash)
if(NOT final_hash STREQUAL original_hash)
    message(FATAL_ERROR "Source archive changed")
endif()
